### PR TITLE
♿️(frontend) fix sidebar resize handle for screen readers

### LINKED ISSUE #2110: Resizable separator: inactive with keyboard
## Bug Report

**Problematic behavior**
The resizable separator between the sidebar and the main content is reachable via Tab. The Home and End keys work correctly, but the left and right arrow keys do not allow resizing the panels.

**Expected behavior/code**
The left and right arrow keys must allow progressive resizing of the sidebar, just as Home and End allow reaching the extreme values.

**Steps to Reproduce**
1. Open a document in Docs
2. Navigate with the keyboard using Tab to the resizable separator
3. Press the left and right arrow keys
4. The panels do not resize — unlike Home and End which work

**Possible Solution**
```
<PanelResizeHandle
  onKeyDown={(e) => {
    // Home et End déjà implémentés
    // Ajouter la gestion des flèches
    if (e.key === 'ArrowLeft') resizePanel(-1);
    if (e.key === 'ArrowRight') resizePanel(1);
  }}
/>
```

**Critères RGAA**

**Critère 7.1 :** [Chaque script est-il, si nécessaire, compatible avec les technologies d'assistance ?](https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#7.1)

**Impact**
A user navigating exclusively with the keyboard can reach the separator and toggle between minimum and maximum sizes via Home and End, but cannot perform progressive resizing with the arrow keys.

### PR DESCRIPTION
**Pull request by Ovgodd**
## Purpose

Fix left sidebar keyboard resize with a screen reader on, and improve SR output plus step size.

## Proposal

- [x]  Replace the default separator role with slider so that, when the handle is focused, screen readers pass Left/Right to the app instead of using them for reading (known issue with separator in NVDA).
- [x] from `aria-valuenow` into `aria-valuetext` (width in px).
- [x] Use `keyboardResizeBy={1}` for smaller steps.

### CODE REVIEW

**Comment by AntoLC** [comment]
@CodeRabbit review

File: src/frontend/apps/impress/src/features/left-panel/components/ResizableLeftPanel.tsx [hunk 1]
```diff
@@ -132,6 +180,7 @@ export const ResizableLeftPanel = ({
       </Panel>
       {isPanelOpen && (
         <PanelResizeHandle
+          id={RESIZE_HANDLE_ID}
```
Comment (AntoLC) [inline src/frontend/apps/impress/src/features/left-panel/components/ResizableLeftPanel.tsx:183]: Is the `ref` not working ?

File: src/frontend/apps/impress/src/features/left-panel/components/ResizableLeftPanel.tsx [hunk 2]
```diff
@@ -96,14 +100,58 @@ export const ResizableLeftPanel = ({
...
+
+    const updateValueText = () => {
+      const value = handle.getAttribute('aria-valuenow');
+      if (value) {
+        const widthPx = Math.round(
+          (parseFloat(value) / 100) * window.innerWidth,
+        );
+        handle.setAttribute(
+          'aria-valuetext',
+          t('Sidebar width: {{widthPx}} pixels', { widthPx }),
```
Comment (AntoLC) [inline src/frontend/apps/impress/src/features/left-panel/components/ResizableLeftPanel.tsx:130]: Not big fan of the `useEffect`. 
I can see that the role `slider` cannot be set directly to the component, fair enough to set it in the useEffect, but the other props can be set directly to the component.

We can do somethink like:
```tsx
<PanelResizeHandle
          id={RESIZE_HANDLE_ID}
          ...
          aria-orientation="vertical"
          aria-label={t('Resize sidebar')}
          aria-valuetext={t('Sidebar width: {{widthPx}} pixels', {
            widthPx: Math.round((panelSizePercent / 100) * window.innerWidth),
          })}
        />
```

Seems more clean than using the `seEffect` to mutate the component, wdyt ?

File: src/frontend/apps/impress/src/features/left-panel/components/ResizableLeftPanel.tsx [hunk 3]
```diff
@@ -96,14 +100,58 @@ export const ResizableLeftPanel = ({
...
+
   const handleResize = (sizePercent: number) => {
     const widthPx = (sizePercent / 100) * window.innerWidth;
     savedWidthPxRef.current = widthPx;
     setPanelSizePercent(sizePercent);
   };
 
   return (
-    <PanelGroup direction="horizontal">
+    <PanelGroup direction="horizontal" keyboardResizeBy={1}>
```
[the remark this answers is not in the document]
Comment (Ovgodd) [reply src/frontend/apps/impress/src/features/left-panel/components/ResizableLeftPanel.tsx:147]: it is supported in our current version

`    autoSaveId?: string | null;
    className?: string;
    direction: Direction;
    id?: string | null;
    keyboardResizeBy?: number | null;
    onLayout?: PanelGroupOnLayout | null;
    storage?: PanelGroupStorage;
    style?: CSSProperties;
    tagName?: keyof HTMLElementTagNameMap;
    dir?: "auto" | "ltr" | "rtl" | undefined;
}>;`

File: src/frontend/apps/impress/src/features/left-panel/components/ResizableLeftPanel.tsx (hunk 1 above)
Comment (Ovgodd) [reply src/frontend/apps/impress/src/features/left-panel/components/ResizableLeftPanel.tsx:176]: indeed PanelResizeHandle does not declare `RefAttributes<HTMLDivElement>` in its types (v3.0.6).

File: src/frontend/apps/impress/src/features/left-panel/components/ResizableLeftPanel.tsx (hunk 2 above)
Comment (Ovgodd) [reply src/frontend/apps/impress/src/features/left-panel/components/ResizableLeftPanel.tsx]: Yes, good idea! I moved aria-orientation, aria-label and aria-valuetext directly to the component. I also changed the SR announcement instead of a raw percentage, it now says narrow, medium or wide based on the position within the allowed range, which feels more natural for screen reader users.

File: src/frontend/apps/impress/src/features/left-panel/components/ResizableLeftPanel.tsx [hunk 4]
```diff
@@ -132,6 +169,26 @@ export const ResizableLeftPanel = ({
...
+              maxPanelSizePercent,
+            );
+            if (label === 'narrow') {
+              return t('Sidebar width: narrow');
+            }
+            if (label === 'medium') {
+              return t('Sidebar width: medium');
+            }
+            return t('Sidebar width: wide');
+          })()}
```
Comment (AntoLC) [inline src/frontend/apps/impress/src/features/left-panel/components/ResizableLeftPanel.tsx]: We can maybe simplify a little bit, then directly in the function you can call `t('Sidebar width: narrow')`

```suggestion
          aria-valuetext={getValueLabel(
            panelSizePercent,
            minPanelSizePercent,
            maxPanelSizePercent,
            t
          )}
```

**Review by AntoLC — APPROVED** [review]
Like pointed the rabbit, you should probably managed this case `max === min`.

File: src/frontend/apps/impress/src/features/left-panel/components/ResizableLeftPanel.tsx (hunk 4 above)
Comment (Ovgodd) [reply src/frontend/apps/impress/src/features/left-panel/components/ResizableLeftPanel.tsx]: good point !
